export const INITIATOR = {
  USER: 'USER',
  CLIENT: 'CLIENT',
};

export const STATUS_PLAYED_ROUTINE = {
  STARTED_WP: 'STARTED_WP',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED',
  FINISHED: 'FINISHED',
  COMPLETED: 'COMPLETED',
  NOT_COMPLETED: 'NOT_COMPLETED',
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
};

export const STATUS_PLAYED_ACTIVITY = {
  NOT_STARTED: 'NOT_STARTED',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  CANCELED: 'CANCELED',
};

export const PROMPTS_OPTIONS = {
  NONE: 'None',
  VERBAL: 'Verbal',
  GESTURE: 'Gesture',
  MODEL: 'Model',
  PHYSICAL_PARTIAL: 'Physical (partial)',
  PHYSICAL_FULL: 'Physical (full)',
};
