export const INITIATOR = {
  USER: 'USER',
  CLIENT: 'CLIENT',
};

export const STATUS_PLAYED_CHECKLIST = {
  STARTED_WP: 'STARTED_WP',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  STOPPED: 'STOPPED',
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
};

export const STATUS_PLAYED_ACTIVITY = {
  NOT_STARTED: 'NOT_STARTED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};
