export const SLEEP_MODE = {
  MIN_SLEEP_DURATION: 10,
  MAX_SLEEP_DURATION: 1080,
  MIN_AUDIO_DURATION: 0,
  MAX_AUDIO_DURATION: 240,
  MIN_VISUAL_DURATION: 0,
  MAX_VISUAL_DURATION: 240,
  MIN_BACK_TO_BED_DURATION: 0,
  MAX_BACK_TO_BED_DURATION: 240,
  MIN_VOLUME: 0,
  MAX_VOLUME: 100,
  MIN_BRIGHTNESS: 0,
  MAX_BRIGHTNESS: 100,
};

export const AUDIO_TYPES = {
  SILENT: 'SILENT',
  USER_UPLOADED: 'USER_UPLOADED',
  SYSTEM_UPLOADED: 'SYSTEM_UPLOADED',
};
