export const USER_SORT_FIELDS = {
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  EMAIL: 'email',
  TYPE: 'type',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
  NUM_OF_LEARNERS: 'numOfLearners',
  NUM_OF_INVITES_SENT: 'numOfInvitesSent',
  NUM_OF_INVITES_RECEIVED: 'numOfInvitesReceived',
  NUM_OF_SUBSCRIPTIONS: 'numOfsubscriptions',
  SUBSCRIPTIONS: 'subscriptions',
  STATE: 'state',

  FIRST_NAME_DESC: '-firstName',
  LAST_NAME_DESC: '-lastName',
  EMAIL_DESC: '-email',
  TYPE_DESC: '-type',
  CREATED_AT_DESC: '-createdAt',
  UPDATED_AT_DESC: '-updatedAt',
  NUM_OF_LEARNERS_DESC: '-numOfLearners',
  NUM_OF_INVITES_SENT_DESC: '-numOfInvitesSent',
  NUM_OF_INVITES_RECEIVED_DESC: '-numOfInvitesReceived',
  NUM_OF_SUBSCRIPTIONS_DESC: '-numOfsubscriptions',
  SUBSCRIPTIONS_DESC: '-subscriptions',
  STATE_DESC: '-state',
};

export const COMPLETED_ROUTINE_SORT_FIELDS = {
  STARTED_AT_WEB_PORTAL: 'startedAtWebPortal',
  STARTED_AT_DEVICE: 'startedAtDevice',
  STATUS: 'status',
  CREATED_AT: 'createdAt',
  FINISHED_AT: 'finishedAt',
  ROUTINE_NAME: 'routineName',
  DEVICE_ID: 'deviceId',

  STARTED_AT_WEB_PORTAL_DESC: '-startedAtWebPortal',
  STARTED_AT_DEVICE_DESC: '-startedAtDevice',
  STATUS_DESC: '-status',
  CREATED_AT_DESC: '-createdAt',
  FINISHED_AT_DESC: '-finishedAt',
  ROUTINE_NAME_DESC: '-routineName',
  DEVICE_ID_DESC: '-deviceId',
};

export const CLIENT_SORT_FIELDS = {
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  DEVICE_ID: 'deviceId',
  DATE_OF_BIRTH: 'dateOfBirth',
  DIAGNOSIS: 'diagnosis',
  SCHOOL_NAME: 'schoolName',
  TEACHER_NAME: 'teacherName',
  SUBSCRIPTIONS: 'subscriptions',
  CREATED_AT: 'createdAt',
  // COMPLETED_AT: 'lastRoutineCompletedAt',
  NUM_OF_REWARDS: 'numOfRewards',
  NUM_OF_INVITES_SENT: 'numOfInvitesSent',
  NUM_OF_ROUTINES: 'numOfRoutines',
  NUM_OF_ADULTS: 'numOfAdults',

  FIRST_NAME_DESC: '-firstName',
  LAST_NAME_DESC: '-lastName',
  DEVICE_ID_DESC: '-deviceId',
  DATE_OF_BIRTH_DESC: '-dateOfBirth',
  DIAGNOSIS_DESC: '-diagnosis',
  SCHOOL_NAME_DESC: '-schoolName',
  TEACHER_NAME_DESC: '-teacherName',
  SUBSCRIPTIONS_DESC: '-subscriptions',
  CREATED_AT_DESC: '-createdAt',
  // COMPLETED_AT_DESC: '-lastRoutineCompletedAt',
  NUM_OF_REWARDS_DESC: '-numOfRewards',
  NUM_OF_INVITES_SENT_DESC: '-numOfInvitesSent',
  NUM_OF_ROUTINES_DESC: '-numOfRoutines',
  NUM_OF_ADULTS_DESC: '-numOfAdults',
};
