const USER_TYPES = {
  PARENT: 'PARENT',
  GRANDPARENT: 'GRANDPARENT',
  NANNY: 'NANNY',
  OTHER_RELATIVE: 'OTHER_RELATIVE',
  OTHER_FRIEND: 'OTHER_FRIEND',
  ABA_PROFESSIONAL: 'ABA_PROFESSIONAL',
  OCCUPATIONAL_THERAPIST: 'OCCUPATIONAL_THERAPIST',
  SL_PATHOLOGIST: 'SL_PATHOLOGIST',
  PSYCHOLOGIST: 'PSYCHOLOGIST',
  TEACHER: 'TEACHER',
  COACH: 'COACH',
  OTHER_PROFESSIONAL: 'OTHER_PROFESSIONAL',
};
export { USER_TYPES };
