version: '3.8'
services:
  back_app:
    labels:
      description: 'API'
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - '3000:3000'
    env_file: .env.local
    environment:
      - DB_URL=mongodb://db_mongo/goally_migration_test
      - NODE_ENV=LOCAL
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/static/uploads

  db:
    image: mongo
    container_name: db_mongo
    env_file: .env.local
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
    env_file:
      - .env.local
    command: ['redis-server', '--appendonly', 'yes']
    restart: unless-stopped

volumes:
  mongodata:
