export const FCM_CLIENT_EVENTS = {
  WAKE_UP: 'WAKE_UP',
  START_ROUTINE: 'START_ROUTINE',
  START_CHECKLIST: 'START_CHECKLIST',
  START_SLEEP_MODE: 'START_SLEEP_MODE',
  STOP_SLEEP_MODE: 'STOP_SLEEP_MODE',
  START_REMINDER: 'START_REMINDER',
  BEHAVIOR_RECORDED: 'BEHAVIOR_RECORDED',
  REWARD_REDEEMED: 'REWARD_REDEEMED',
  SLEEP_MODE: 'SLEEP_MODE',
  ADD_DEVICE: 'ADD_DEVICE',
  SYNC_LOGS: 'SYNC_LOGS',
};

export const FCM_USER_EVENTS = {
  ROUTINE_COMPLETE: 'Routine Completed',
  ROUTINE_STARTED: 'Routine Started',
  BEHAVIOR_RECORDED: 'Behavior Recorded',
  REWARD_REDEEMED: 'Reward Redeemed',
};
