export const defaultLabWords = [
  {
    name: 'Away',
    imgUrl: 'word_lab/images/away.svg',
    bgImgUrl: 'word_lab/bg_images/pink_box.png',
    ordering: 0,
    clientId: null,
    video1: 'word_lab/videos/WordLab_Away_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Away_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Away_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Away_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Away_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Away_Sec6.mp4',
  },
  {
    name: 'What',
    imgUrl: 'word_lab/images/what.svg',
    bgImgUrl: 'word_lab/bg_images/pink_box.png',
    ordering: 1,
    clientId: null,
    video1: 'word_lab/videos/WordLab_What_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_What_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_What_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_What_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_What_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_What_Sec6.mp4',
  },
  {
    name: 'Same',
    imgUrl: 'word_lab/images/same.svg',
    bgImgUrl: 'word_lab/bg_images/blue_box.png',
    ordering: 2,
    clientId: null,
    video1: 'word_lab/videos/WordLab_Same_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Same_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Same_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Same_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Same_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Same_Sec6.mp4',
  },
  {
    name: 'Different',
    imgUrl: 'word_lab/images/different.svg',
    bgImgUrl: 'word_lab/bg_images/blue_box.png',
    ordering: 3,
    clientId: null,
    video1: 'word_lab/videos/WordLab_Different_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Different_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Different_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Different_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Different_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Different_Sec6.mp4',
  },
  {
    name: 'Come',
    imgUrl: 'word_lab/images/come.svg',
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    ordering: 4,
    clientId: null,
    video1: 'word_lab/videos/WordLab_Come_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Come_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Come_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Come_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Come_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Come_Sec6.mp4',
  },
  {
    name: 'Want',
    imgUrl: 'word_lab/images/want.svg',
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    ordering: 5,
    clientId: null,
    video1: 'word_lab/videos/WordLab_Want_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Want_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Want_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Want_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Want_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Want_Sec6.mp4',
  },
  {
    name: 'No',
    imgUrl: 'word_lab/images/no.svg',
    bgImgUrl: 'word_lab/bg_images/brown_box.png',
    ordering: 6,
    clientId: null,
    video1: 'word_lab/videos/WordLab_No_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_No_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_No_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_No_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_No_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_No_Sec6.mp4',
  },
  {
    name: 'Like',
    imgUrl: 'word_lab/images/like.svg',
    ordering: 7,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_Like_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Like_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Like_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Like_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Like_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Like_Sec6.mp4',
  },
  {
    name: 'More',
    imgUrl: 'word_lab/images/more.svg',
    bgImgUrl: 'word_lab/bg_images/blue_box.png',
    ordering: 8,
    clientId: null,
    video1: 'word_lab/videos/WordLab_More_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_More_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_More_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_More_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_More_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_More_Sec6.mp4',
  },
  {
    name: 'Go',
    imgUrl: 'word_lab/images/go.svg',
    ordering: 9,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_Go_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_Go_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_Go_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_Go_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_Go_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_Go_Sec6.mp4',
  },
  {
    name: 'Up',
    imgUrl: 'word_lab/images/up.svg',
    ordering: 10,
    bgImgUrl: 'word_lab/bg_images/pink_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_UP_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_UP_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_UP_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_UP_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_UP_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_UP_Sec6.mp4',
  },
  {
    name: 'Down',
    imgUrl: 'word_lab/images/down.svg',
    ordering: 11,
    bgImgUrl: 'word_lab/bg_images/pink_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_DOWN_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_DOWN_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_DOWN_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_DOWN_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_DOWN_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_DOWN_Sec6.mp4',
  },
  {
    name: 'Mad',
    imgUrl: 'word_lab/images/mad.svg',
    ordering: 12,
    bgImgUrl: 'word_lab/bg_images/blue_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_MAD_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_MAD_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_MAD_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_MAD_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_MAD_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_MAD_Sec6.mp4',
  },
  {
    name: 'Eat',
    imgUrl: 'word_lab/images/eat.svg',
    ordering: 13,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_EAT_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_EAT_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_EAT_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_EAT_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_EAT_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_EAT_Sec6.mp4',
  },
  {
    name: 'Drink',
    imgUrl: 'word_lab/images/drink.svg',
    ordering: 14,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_DRINK_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_DRINK_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_DRINK_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_DRINK_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_DRINK_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_DRINK_Sec6.mp4',
  },
  {
    name: 'Help',
    imgUrl: 'word_lab/images/help.svg',
    ordering: 15,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_HELP_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_HELP_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_HELP_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_HELP_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_HELP_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_HELP_Sec6.mp4',
  },
  {
    name: 'Hurt',
    imgUrl: 'word_lab/images/hurt.svg',
    ordering: 16,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_HURT_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_HURT_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_HURT_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_HURT_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_HURT_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_HURT_Sec6.mp4',
  },
  {
    name: 'Play',
    imgUrl: 'word_lab/images/play.svg',
    ordering: 17,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_PLAY_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_PLAY_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_PLAY_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_PLAY_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_PLAY_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_PLAY_Sec6.mp4',
  },
  {
    name: 'Sleep',
    imgUrl: 'word_lab/images/sleep.svg',
    ordering: 18,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_SLEEP_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_SLEEP_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_SLEEP_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_SLEEP_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_SLEEP_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_SLEEP_Sec6.mp4',
  },
  {
    name: 'Stop',
    imgUrl: 'word_lab/images/stop.svg',
    ordering: 19,
    bgImgUrl: 'word_lab/bg_images/green_box.png',
    clientId: null,
    video1: 'word_lab/videos/WordLab_STOP_Sec1.mp4',
    video2: 'word_lab/videos/WordLab_STOP_Sec2.mp4',
    video3: 'word_lab/videos/WordLab_STOP_Sec3.mp4',
    video4: 'word_lab/videos/WordLab_STOP_Sec4.mp4',
    video5: 'word_lab/videos/WordLab_STOP_Sec5.mp4',
    video6: 'word_lab/videos/WordLab_STOP_Sec6.mp4',
  },
];
